plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.139'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories{
    maven {
        //JEI
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        url 'https://maven.blamejared.com'
    }

    maven {
        //JEI
        url 'https://modmaven.dev/'
    }

    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    // LDLib2
    maven {
        url = "https://maven.firstdark.dev/snapshots"
    }

    //modrinth
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"

        }
    }

    //curios
    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }

    //geckolib
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup("software.bernie.geckolib")
        }
    }

    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}

dependencies {
    //JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    //jade
    implementation "curse.maven:jade-324717:7428884"

    //ae2
    implementation "curse.maven:applied-energistics-2-223794:7027323"
    implementation "curse.maven:guideme-1173950:7127444"

    //ae2cs
    implementation "curse.maven:ae2-crystal-science-1435174:8068871"
    //glodium
    implementation "curse.maven:glodium-957920:5821676"
    //extended ae
    implementation "curse.maven:ex-pattern-provider-892005:8025439"
    //advanced ae
    implementation "curse.maven:advancedae-1084104:7849217"
    //ae2lt
    implementation "curse.maven:ae2-lightning-tech-1527395:8101595"

    //titanium
    implementation "curse.maven:titanium-287342:6875285"
    //function storage
    implementation "curse.maven:functional-storage-556861:7061714"
    //industrial foregoing
    implementation("maven.modrinth:industrial-foregoing:${industrialforegoing_version}")

    //mekanism
    implementation "curse.maven:mekanism-268560:7621971"

    //ldlib
    implementation("com.lowdragmc.ldlib2:ldlib2-neoforge-${minecraft_version}:${ldlib2_version}:all")

    //KubeJS
    implementation "curse.maven:kubejs-238086:7255073"
    implementation "curse.maven:rhino-416294:7104526"
    //kubejs mekanism
    implementation "curse.maven:kubejs-mekanism-418651:7213666"

    //bookshelf
    implementation "curse.maven:bookshelf-228525:7335846"
    //prickle
    implementation "curse.maven:prickle-1023259:6961457"
    //botany pot
    implementation "curse.maven:botany-pots-353928:7115287"
    //botany pot tiers
    implementation "curse.maven:botany-pots-tiers-526754:7209522"

    //cucumber
    implementation "curse.maven:cucumber-272335:7180790"
    //mystical agriculture
    implementation "curse.maven:mystical-agriculture-246640:7397787"
    //mystical agradditions
    implementation "curse.maven:mystical-agradditions-256247:7397775"

    //mekanism extra
    implementation "curse.maven:mekanism-extras-1026040:7628313"

    //mekanism unleashed
    implementation "curse.maven:mekanism-unleashed-1072209:6487994"

    //curios
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"

    //geckolib
    implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"

    //terra blender
    implementation "com.github.glitchfiend:TerraBlender-neoforge:${minecraft_version}-${terrablender_version}"

    //ars nouveau
    implementation "com.hollingsworth.ars_nouveau:ars_nouveau-${minecraft_version}:${ars_version}"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
